version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-db_2025_ds
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_2025_ds:/var/lib/postgresql/data
    networks:
      - prisma-network_2025_ds
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 2s
      retries: 20
    logging:
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgres_data_2025_ds:
    driver: local

networks:
  prisma-network_2025_ds:
    driver: bridge